In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv('cened_milano_pulito.csv')
df.head()

,RESIDENZIALE,NON_RESIDENZIALE,CLASSIFICAZIONE_DPR,INTERO_EDIFICIO,UNITA_IMMOBILIARE,NUMERO_UNITA_IMMOBILIARI,NUOVA_COSTRUZIONE,RISTRUTTURAZIONE_IMPORTANTE,RIQUALIFICAZIONE_ENERGETICA,COMUNE,...,CLIMATIZZAZIONE_ESTIVA,VENTILAZIONE_MECCANICA,PROD_ACQUA_CALDA_SANITARIA,VETTORE_ENERGETICO,CI_TIPO_IMPIANTO_1,CI_ANNO_INSTALLAZIONE_1,CI_VETTORE_ENERGETICO_1,CI_POTENZA_NOMINALE_1,CI_EFFICIENZA_MEDIA,CLASSE_BUONA
0,True,False,E.1(1),False,True,1,False,False,False,MILANO,...,False,False,True,NaN,Generatore a combustione,2006.0,Gas naturale,450.0,0.84,0
1,False,True,E.5,False,True,14,False,False,False,MILANO,...,False,False,False,NaN,NaN,NaN,NaN,NaN,0.73,0
2,True,False,E.1(1),False,True,1,False,False,False,MILANO,...,False,False,True,NaN,Generatore a combustione,2008.0,Gas naturale,6.0,0.74,0
3,True,False,E.1(1),False,True,1,False,False,False,MILANO,...,True,False,True,NaN,Teleriscaldamento,1997.0,Teleriscaldamento,750.0,0.58,0
4,True,False,E.1(1),False,True,38,False,False,False,MILANO,...,False,False,True,NaN,Generatore a combustione,2005.0,Gas naturale,290.1,0.80,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 415217 entries, 0 to 415216
Data columns (total 27 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   RESIDENZIALE                 415217 non-null  bool
 1   NON_RESIDENZIALE             415217 non-null  bool
 2   CLASSIFICAZIONE_DPR          415217 non-null  str
 3   INTERO_EDIFICIO              415217 non-null  bool
 4   UNITA_IMMOBILIARE            415217 non-null  bool
 5   NUMERO_UNITA_IMMOBILIARI     415217 non-null  int64
 6   NUOVA_COSTRUZIONE            415217 non-null  bool
 7   RISTRUTTURAZIONE_IMPORTANTE  415217 non-null  bool
 8   RIQUALIFICAZIONE_ENERGETICA  415217 non-null  bool
 9   COMUNE                       415217 non-null  str
 10  ZONA_CLIMATICA               415217 non-null  str
 11  ANNO_COSTRUZIONE             415217 non-null  str
 12  SUPERF_UTILE_RISCALDATA      415217 non-null  float64
 13  VOLUME_LORDO_RISCALDATO      415217 non-null  float64
 14  SUPERFICIE_DISPERDENTE       415217 non-null  float64
 15  RAPPORTO_SV                  415217 non-null  float64
 16  CLIMATIZZAZIONE_INVERNALE    415217 non-null  bool
 17  CLIMATIZZAZIONE_ESTIVA       415217 non-null  bool
 18  VENTILAZIONE_MECCANICA       415217 non-null  bool
 19  PROD_ACQUA_CALDA_SANITARIA   415217 non-null  bool
 20  VETTORE_ENERGETICO           15261 non-null   str
 21  CI_TIPO_IMPIANTO_1           407579 non-null  str
 22  CI_ANNO_INSTALLAZIONE_1      393137 non-null  float64
 23  CI_VETTORE_ENERGETICO_1      407579 non-null  str
 24  CI_POTENZA_NOMINALE_1        393210 non-null  float64
 25  CI_EFFICIENZA_MEDIA          415217 non-null  float64
 26  CLASSE_BUONA                 415217 non-null  int64
dtypes: bool(11), float64(7), int64(2), str(7)
memory usage: 55.0 MB

In [5]:
df.describe()

,NUMERO_UNITA_IMMOBILIARI,SUPERF_UTILE_RISCALDATA,VOLUME_LORDO_RISCALDATO,SUPERFICIE_DISPERDENTE,RAPPORTO_SV,CI_ANNO_INSTALLAZIONE_1,CI_POTENZA_NOMINALE_1,CI_EFFICIENZA_MEDIA,CLASSE_BUONA
count,415217.000000,4.152170e+05,4.152170e+05,4.152170e+05,415217.000000,393137.000000,3.932100e+05,4.152170e+05,415217.000000
mean,29.714007,1.741340e+02,7.765865e+02,1.976949e+02,0.429349,2011.057056,5.762923e+02,1.064778e+06,0.230708
std,49.814715,3.288960e+04,1.398931e+05,2.954238e+03,0.225688,9.751490,3.636787e+04,6.861050e+08,0.421287
min,1.000000,1.100000e-01,3.600000e-01,0.000000e+00,0.000000,1870.000000,2.000000e-02,-3.501400e+02,0.000000
25%,1.000000,4.391000e+01,1.775100e+02,6.448000e+01,0.279100,2006.000000,2.670000e+01,6.800000e-01,0.000000
50%,16.000000,6.183000e+01,2.455000e+02,9.555000e+01,0.380500,2012.000000,1.953000e+02,7.600000e-01,0.000000
75%,40.000000,8.928000e+01,3.540900e+02,1.512200e+02,0.549200,2018.000000,4.000000e+02,8.500000e-01,0.000000
max,7171.000000,2.114223e+07,8.973797e+07,1.217898e+06,31.056500,2100.000000,9.300000e+06,4.421077e+11,1.000000

## Per evitare leakage facciamo la divisione in train e test

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Survived'])
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y )